controllers/BotController.php
<?php


namespace app\controllers;


use app\components\TelegramComponent;
use app\models\bot\Bot;
use app\models\bot\BotSearch;
use app\models\bot\RegisterBotForm;
use app\models\User;
use RuntimeException;
use Throwable;
use yii\base\InvalidConfigException;
use yii\db\StaleObjectException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\httpclient\Exception;
use yii\web\Controller;
use yii\web\Response;

class BotController extends Controller
{

    /**
     * @return array[]
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],
                    [
                        'actions' => ['create', 'delete', 'update', 'webhook'],
                        'allow' => true,
                        'roles' => [User::ROLE_MODER],
                    ],
                    [
                        'actions' => ['create', 'delete', 'update', 'webhook'],
                        'allow' => false,
                        'roles' => [User::ROLE_USER],
                        'denyCallback' => function ($rule, $action) {
                            return $action->controller->redirect(['bot/index']);
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'create' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new BotSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * @return string
     */
    public function actionCreate(): string
    {
        $model = new RegisterBotForm();
        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $botModel = new Bot([
                'token' => $model->token,
                'path' => $model->path,
                'title' => $model->title,
                'webhooks_is_set' => $model->webhooks_is_set,
                'controller_name' => $model->controller_name,
            ]);

            $botModel->save();

            $this->redirect(['index']);
        }

        return $this->render('_create', compact('model'));
    }

    /**
     * @param int $id
     * @return Response
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete(int $id): Response
    {
        $user = Bot::findOne($id);
        $user->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @param bool $webhook
     * @return Response
     * @throws Exception|InvalidConfigException
     */
    public function actionWebhook(int $id, bool $webhook): Response
    {
        $bot = Bot::findOne($id);
        $telegram = new TelegramComponent(['token' => $bot->token]);

        if ($webhook) {
            try {
                $telegram->deleteWebhook();
                Bot::updateAll(['webhooks_is_set' => Bot::WEBHOOKS_IS_NO_SET], ['id' => $id]);
            } catch (RuntimeException $exception) {
                throw new Exception('Не удалось удалить вебхуки');
            }
        } else {
            try {
                $telegram->setWebhook(Url::to([$bot->controller_name . '/index', 'token' => $telegram->token], true));
                Bot::updateAll(['webhooks_is_set' => Bot::WEBHOOKS_IS_SET], ['id' => $id]);
            } catch (RuntimeException $exception) {
                throw new Exception('Не удалось установить вебхуки');
            }
        }

        return $this->redirect(['index']);
    }

    public function actionUpdate(int $id)
    {
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\user\search\UserSearch;
use SodiumException;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
    /**
     * @return array[]
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'login'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['config'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public function actions(): array
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search();

        return $this->render('index', compact('dataProvider'));
    }


    /**
     * @return string
     * @throws SodiumException
     */
    public function actionLogin(): string
    {
        if (!\Yii::$app->user->isGuest) {
            $this->redirect('index');
        }

        $model = new LoginForm();
        $params = Yii::$app->request->post();

        if ($params !== [] && $model->load($params) && $model->validate()) {
            $user = User::findOne(['username' => $model->username]);

            if ($user !== null && sodium_crypto_pwhash_str_verify($user->password, $model->password)) {
                $model->password = password_hash($model->password, PASSWORD_ARGON2I);
                $model->login();

                $this->redirect('index');
            }

            $model->addError('username', 'Не правильное имя пользователя или пароль');
        }

        return $this->render('login', compact('model'));
    }

    /**
     * @return void
     */
    public function actionLogout(): void
    {
        \Yii::$app->user->logout();

        $this->redirect('login');
    }

    public function actionConfig()
    {
        phpinfo();
    }

}

controllers/UserController.php
<?php


namespace app\controllers;


use app\models\user\RegisterUserForm;
use app\models\User;
use app\models\user\search\UserSearch;
use Exception;
use Throwable;
use yii\db\StaleObjectException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use \yii\web\Response;

class UserController extends Controller
{
    /**
     * @return array[]
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => [],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],
                    [
                        'actions' => ['create', 'delete', 'update'],
                        'allow' => true,
                        'roles' => [User::ROLE_MODER],
                    ],
                    [
                        'actions' => ['create', 'delete', 'update'],
                        'allow' => false,
                        'roles' => [User::ROLE_USER],
                        'denyCallback' => function ($rule, $action) {
                            return $action->controller->redirect(['user/index']);
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'create' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $params = \Yii::$app->request->get();

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search($params);

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionCreate(): string
    {
        $model = new RegisterUserForm();
        $request = \Yii::$app->request;

        if ($request->isPost && $model->load($request->post()) && $model->validate()) {
            $user = new User([
                'email' => $model->email,
                'username' => $model->username,
                'authKey' => hash('sha256', random_bytes(5)),
                'accessToken' => hash('sha256', random_bytes(5)),
                'password' => password_hash($model->password, PASSWORD_ARGON2I),
            ]);

            $user->save();

            $auth = \Yii::$app->authManager;
            $userRole = $auth->getRole($model->role ?: User::ROLE_USER);
            $auth->assign($userRole, $user->getId());

            $this->redirect('/user/index');
        }

        return $this->render('_create', compact('model'));
    }

    /**
     * @param int $id
     * @return Response
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete(int $id): Response
    {
        $user = User::findOne($id);
        $user->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return string
     */
    public function actionUpdate(int $id): string
    {
        $params = \Yii::$app->request->post();
        $user = User::findOne($id);

        if ($user->load($params) && $user->validate()) {
            $user->password = password_hash($user->password, PASSWORD_ARGON2I);
            $user->save();
        }

        return $this->render('_reset_password', compact('user'));
    }

}

views/layouts/content.php
<?php
/**
 * @var $content string
 */

use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Alert;
use yii\helpers\Html;
use yii\helpers\Inflector;

?>
<div class="container-fluid">

    <div class="row">
        <div class="col-md-5 ml-4">
            <div class="d-sm-flex align-items-center justify-content-start mb-4">
                <?php if (!\Yii::$app->user->isGuest): ?>
                    <?php if (isset($this->blocks['content-header'])) : ?>
                        <h1 class="h3 mb-0 text-gray-800"><?=$this->blocks['content-header']?></h1>
                    <?php else : ?>
                        <div class="h3 mb-0 text-gray-800">
                            <?php if ($this->title !== null) : ?>
                                <?=Html::encode($this->title);?>
                            <?php else : ?>
                                <?=Inflector::camel2words(
                                    Inflector::id2camel($this->context->module->id)
                                );?>
                                <?=($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php if (Yii::$app->getSession()->getAllFlashes()) {
                foreach (Yii::$app->getSession()->getAllFlashes() as $key => $value) {
                    echo Alert::widget([
                        'options' => [
                            'class' => 'alert-' . $key,
                        ],
                        'body' => $value,
                    ]);
                }
            } ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?=$content?>
        </div>
    </div>
</div>

views/layouts/header.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;

?>

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow rounded-bottom">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><?=User::findOne(Yii::$app->user->id)->username?></span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/random/60x60">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="<?=Url::to(['user/profile/' . Yii::$app->user->id]);?>">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Профиль
                </a>
                <a class="dropdown-item" href="<?=Url::to(['site/setting/' . Yii::$app->user->id]);?>">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Настройки
                </a>
                <?php if (\Yii::$app->user->identity->isAdmin()): ?>
                    <a class="dropdown-item" href="<?=Url::to(['site/config']);?>">
                        <i class="fas fa-server fa-sm fa-fw mr-2 text-gray-400"></i>
                        Конфигурация сервера
                    </a>
                <?php endif; ?>
                <div class="dropdown-divider"></div>
                <?=Html::a(
                    'Выход',
                    ['site/logout'],
                    ['data-method' => 'get', 'class' => 'dropdown-item']
                )?>
            </div>
        </li>
    </ul>
</nav>

views/layouts/main.php
<?php
/**
 * @var $content string
 */

use app\assets\AppAsset;
use hoaaah\sbadmin2\assets\SbAdmin2Asset;
use yii\helpers\Html;

AppAsset::register($this);
SbAdmin2Asset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@bower/startbootstrap-sb-admin-2');
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body id="page-top">

<?php $this->beginBody() ?>

<div id="wrapper">


    <?php if (!\Yii::$app->user->isGuest): ?>
        <?= $this->render(
            'sidebar.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>
    <?php endif; ?>

    <div id="content-wrapper" class="d-flex flex-column">

        <div id="content">

            <?php if (!\Yii::$app->user->isGuest): ?>
                <?= $this->render(
                    'header.php',
                    ['directoryAsset' => $directoryAsset]
                ) ?>
            <?php endif; ?>


            <?= $this->render(
                'content.php',
                ['content' => $content, 'directoryAsset' => $directoryAsset]
            ) ?>

        </div>

    </div>

</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/sidebar.php
<?php

use hoaaah\sbadmin2\widgets\Menu;

?>

<?=Menu::widget([
    'options' => [
        'ulClass' => "navbar-nav sidebar bg-gradient-success rounded-right sidebar-dark accordion",
        'ulId' => "accordionSidebar",
    ],
    'brand' => [
        'url' => ['/'],
        'content' => <<<HTML
            <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-robot"></i>
            </div>
            <div class="sidebar-brand-text mx-3">www.atb.ru</div>
        HTML,
    ],
    'items' => [
        [
            'label' => 'Dashboard',
            'url' => ['/site/index'],
            'icon' => 'fas fa-fw fa-tachometer-alt',
            'visible' => true,
        ],
        [
            'label' => 'Статистика',
            'icon' => 'fa fa-chart-line',
            'url' => ['#'],
        ],
        [
            'label' => 'Боты',
            'icon' => 'fa fa-robot',
            'items' => [
                [
                    'label' => 'Список',
                    'icon' => 'fa fa-list',
                    'url' => ['/bot/index'],
                ],
                [
                    'label' => 'Добавить нового',
                    'icon' => 'fa fa-plus',
                    'url' => ['/bot/create'],
                    'visible' => \Yii::$app->user->identity->isAdmin(),
                ],
            ],
        ],
        [
            'label' => 'Пользователи',
            'icon' => 'fa fa-user',
            'visible' => true,
            'items' => [
                [
                    'label' => 'Список',
                    'icon' => 'fa fa-list',
                    'url' => ['/user/index'],
                ],
                [
                    'label' => 'Добавить нового',
                    'icon' => 'fa fa-user-plus',
                    'url' => ['/user/create'],
                    'visible' => \Yii::$app->user->identity->isAdmin(),
                ],
            ],
        ],
        [
            'label' => 'Телеграм',
            'icon' => 'fa fa-at',
            'items' => [
                [
                    'label' => 'Аккаунты',
                    'url' => /*['/telegram/account']*/ ['#'],
                    'icon' => 'fa fa-users',
                ],
            ],
        ],
    ],
]);